为编辑器添加修改图片alt的选项
halo-sigs/richtext-editor pull request #32
Opened 2023-08-13 15:18 UTC by GodlessLiu

为富文本编辑器添加修改alt属性的按钮：
![image](https://github.com/halo-sigs/richtext-editor/assets/110895612/c4fd921a-01ef-47e3-8ac9-d29748211efe)
点击按钮出现input框，供用户添加alt属性
![image](https://github.com/halo-sigs/richtext-editor/assets/110895612/d865d579-ba1d-4911-99f2-15cd63ec28ee)
Fixes https://github.com/halo-dev/halo/issues/4397

2023-08-14 01:37 UTC, wan92hen commented
建议更换一个跟文本相关的图标。

2023-08-14 10:28 UTC, ruibaby commented
<img width="1674" alt="image" src="https://github.com/halo-sigs/richtext-editor/assets/21301288/69913af6-704b-481a-94ce-98b662ad14a4">

可以用这个

2023-08-14 11:53 UTC, ruibaby requested changes

2023-08-14 11:53 UTC, ruibaby commented on packages/editor/src/locales/zh-CN.yaml
> +      edit_alt: 修改图片alt属性
```suggestion
      edit_alt: 修改图片 alt 属性
```

2023-08-14 11:53 UTC, ruibaby commented on packages/editor/src/locales/zh-CN.yaml
> +      alt_input: 输入图片alt属性值,然后回车确认
```suggestion
      alt_input: 输入图片 alt 属性值，按回车确认
```

2023-08-14 11:53 UTC, ruibaby commented on packages/editor/src/locales/en.yaml
> +      alt_input: Enter the img alt and press enter to confirm.
```suggestion
      alt_input: Enter the image alt and press enter to confirm.
```

2023-08-14 12:03 UTC, ruibaby requested changes

2023-08-14 12:03 UTC, ruibaby commented on packages/editor/src/extensions/image/ImageView.vue
> +import MdLink from "~icons/mdi/text-box-edit-outline";
```suggestion
import MdiTextBoxEditOutline from "~icons/mdi/text-box-edit-outline";
```

2023-08-14 12:03 UTC, ruibaby commented on packages/editor/src/extensions/image/ImageView.vue
> +              <MdLink />
```suggestion
              <MdiTextBoxEditOutline />
```

2023-08-15 08:09 UTC, ruibaby reviewed
/lgtm

Thanks for your first contribution!

2023-08-15 08:10 UTC, ruibaby approved these changes

2023-08-15 08:12 UTC, merged